name: pre-commit

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - '**/*.rst'
      - '**/*.txt'
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - '**/*.rst'
      - '**/*.txt'

jobs:
  run:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
